### ISSUE TITLE
Error on Gentoo -> Solution

### ISSUE THREAD

**Issue by Kurnihil** [ProtonVPN/protonvpn-cli#1]
On gentoo, in mine at least, openvpn fail with the config of your servers because it doesn't have /etc/openvpn/update-resolv-conf.
Saving 
[https://raw.githubusercontent.com/masterkorp/openvpn-update-resolv-conf/master/update-resolv-conf.sh](https://raw.githubusercontent.com/masterkorp/openvpn-update-resolv-conf/master/update-resolv-conf.sh) as /etc/openvpn/update-resolv-conf, and "chmod +x" it, resolve the problem.

Maybe it's possible to check it and auto-add it?

**Comment by xilopaint** [comment]
I got to connect with this tip, but can't navigate in any other site beyond Google.

**Comment by Kurnihil** [comment]
Are you also on Gentoo? Are you using systemd?
For me works everything..
Try to have a look at the repo where i stole the script: [masterkorp repo](https://github.com/masterkorp/openvpn-update-resolv-conf/)

Sorry I'm not able to help you more..

**Comment by xilopaint** [comment]
No, I'm on macOS.

**Comment by xilopaint** [comment]
> On gentoo, in mine at least, openvpn fail with the config of your servers because it doesn't have /etc/openvpn/update-resolv-conf.
> Saving
> https://raw.githubusercontent.com/masterkorp/openvpn-update-resolv-conf/master/update-resolv-conf.sh as /etc/openvpn/update-resolv-conf, and "chmod +x" it, resolve the problem.

I got to connect with this before. I have no idea why it's not working anymore. I should have changed something. :(

**Comment by mazen160** [comment]
Hi @xilopaint @Kurnihil 

I have pushed a fix now. Please test it out, and re-open the ticket if you're still facing issues.

Thanks you for reporting this!

Best,
Mazin

**Comment by mazen160** [comment]
Commit: https://github.com/ProtonVPN/protonvpn-cli/commit/595fc547d73c7e8b5356e1838b0f005d3454bf37
