### ISSUE TITLE
Allow --connect to take a server name so users can connect without navigating the ncurses menu

### ISSUE THREAD

**Issue by njfox** [ProtonVPN/protonvpn-cli#10]
It would be nice if users could directly pass a server name (and optional protocol) to the --connect option so they can connect quickly when they already know what server they want to use. For example:

`sudo protonvpn-cli --connect us-ca#6`

or

`sudo protonvpn-cli --connect us-ca#6 tcp`

**Comment by Rafficer** [comment]
On one hand pretty cool, on the other hand if you connect to the same server every time you can simply use openvpn for that in one line.

**Comment by mazen160** [comment]
Hi @njfox and @Rafficer 

Thanks for making a ticket. We have this on roadmap. The plan is to support both menu and direct connection.

`pvpn --connect  # opens a menu`
`pvpn --connect us-ca#6 tcp  # connects directly to us-ca#6 on tcp`

You can also feel free to submit a PR and we would be happy to merge it :)

**Comment by mazen160** [comment]
Hi @njfox 
Would you mind updating the merge to the current base?
I will work on having the PR you pushed implemented this week :)

Thanks,
Mazin

**Comment by njfox** [comment]
I just resolved the merge conflicts. Did you need me to rebase or will this work?

**Comment by mazen160** [comment]
Hi @njfox 
Just letting you know that the PR has been tested and merged.

Awesome work!

Best,
Mazin
