### ISSUE TITLE
protonvpn-cli -c [server-name] [protocol]

### ISSUE THREAD

**Issue by rascarlo** [ProtonVPN/protonvpn-cli#104]
The usage documentation mentions the command `protonvpn-cli -c [server-name] [protocol]` but I am not able to use it.

When connected to the chosen server, this is the output of `pvpn --status`:
`[OpenVPN Status]: Running`
`[ProtonVPN Status]: Running`
`[Internet Status]: Online`
`[Public IP Address]: xxx.xxx.xxx.xxx`
`[ProtonVPN] [Server Name]: SE-FR#1`
`[ProtonVPN] [OpenVPN Protocol]: UDP`
`[ProtonVPN] [Exit Country]: FR`
`[ProtonVPN] [Tier]: 2`
`[ProtonVPN] [Server Features]: SECURE_CORE`
`[ProtonVPN] [Server Load]: 17`

When trying to connect with `pvpn -c SE-FR#1 UDP`, output is `no matches found: SE-FR#1`.

Is there something that I am missing? 
Thanks

**Comment by Rafficer** [comment]
I like how you censored the public IP but we can just look it up as it's the VPN server anyway :P

Did you run it as root? Are other secure core servers working? E.g. IS-DE#1?

**Comment by Rafficer** [comment]
Can you run `sudo pvpn --update`?

**Comment by rascarlo** [comment]
The problem is the shell. In **zsh** [server-name] has to be quoted, else will fail. The same issue can be reproduced with any server. Maybe you can update the documentation. Thanks

**Comment by Rafficer** [comment]
Let me test, I'm using zsh and never faced that issue...

**Comment by mazen160** [comment]
Hi @rascarlo 

I remember I thought about having this error occurring on my mind before - but I wasn't able to reproduce it somehow back at the time.

I will update the usage documentation to include usage of quotes on this part, just in case of any errors.


Thanks!
Mazin

**Comment by mazen160** [comment]
@Rafficer I do the same too on redacting the public IP that is already public because of VPN name LOL

**Comment by Rafficer** [comment]
I guess it's better to have that habit than not have it :stuck_out_tongue_winking_eye:

**Comment by Rafficer** [comment]
I just tested it with zsh, also got oh-my-zsh and it works without quoting.

**Comment by rascarlo** [comment]
I am using arch linux, zsh 5.5.1
