### ISSUE TITLE
Error connecting to VPN

### ISSUE THREAD

**Issue by paja93** [ProtonVPN/protonvpn-cli#105]
Hi i can't connect any more to any server. Not sure why... i was connected and once it just disconnected and now i can't connect again for days already. So i just get this message Error connecting to VPN, nothing more.

**Comment by Rafficer** [comment]
Did you reboot the device?

**Comment by mazen160** [comment]
Can you try to download a certificate manually from the ProtonVPN website and then use it? Let me know if it's working.

Also, there is a debugging mode at protonvpn-cli.

via the following:
```bash
$ PROTONVPN_CLI_LOG=true pvpn -f
```
Please do it and attach the logs in the ticket.

**Comment by paja93** [comment]
It's working again and i have no clue why or how... For days i had this problem, maybe there was something wrong with the servers?

**Comment by mazen160** [comment]
Hi @paja93 

I assume no, since we haven't received reports regarding issues with the servers. But it's possible that you were connecting to a server that is loaded with many users at the time.

Good to hear everything is now working well on your side:)

Best,
Mazin
