### ISSUE TITLE
Ubuntu 18.04 has python3 but doesn't make it available as 'python' - protonvpn-cli install fails

### ISSUE THREAD

**Issue by rgayler** [ProtonVPN/protonvpn-cli#106]
I am trying to install protonvpn-cli on a fresh install of Ubuntu 18.04. python3 was already installed, but the executable is named python3, not python. Consequently, `protonvpn-cli.sh --install` thinks that python is not installed and aborts.

```
ross@doppio:~$ sudo apt-get install python3
[sudo] password for ross: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.6.5-3).
0 to upgrade, 0 to newly install, 0 to remove and 3 not to upgrade.
ross@doppio:~$ which python3
/usr/bin/python3
ross@doppio:~$ which python
ross@doppio:~$ sudo ./protonvpn-cli.sh --install
[!] Error: python is not installed. Install `python` package to continue.
```

I have worked around it locally by symlinking python to python3, but I'm not convinced that's a robust solution. It's conceivable that I might install something else that wants 'python' to refer to python2.

**Comment by Rafficer** [comment]
`sudo apt install python`?

**Comment by rgayler** [comment]
> The cli needs the python(2) package. Not python3.

OK. That will work. Thanks.

In that case, ProtonVPN need to update some of their Support Center pages because they explicitly say: `sudo apt-get install python3`

I will put some notes here to help anyone who finds this via search, and send a link to ProtonVPN support.

## NOTES:

* Attempting to install protonvpn-cli at 2018-06-10 (I can't find a version number)
* Fresh install of Ubuntu 18.04 doesn't have the `python` command, it only has `python3`
* The protonvpn-cli installer requires the `python` command to be availoable and requires this command to map to python2 (see the comment from @Rafficer above).
* The protonvpn-cli GithHub [readme](https://github.com/ProtonVPN/protonvpn-cli) and the ProtonVPN Support Center [page for the linux client](https://protonvpn.com/support/linux-vpn-tool/) both say that the client requires the `python` command.
* However, the ProtonVPN Support Center [page for the linux client](https://protonvpn.com/support/linux-vpn-tool/) also says to install python with `sudo apt-get install python3`, which is wrong on Ubuntu 18.04.

### FWIW (I am not a Python programmer)

I found this note from python.org on "[The python command on unix-like systems](https://www.python.org/dev/peps/pep-0394/)". It recommends that:

> code that needs to invoke the Python interpreter should not specify python, but rather should specify either python2 or python3

So perhaps if the client *must* use python 2, it should explicitly use `python2` rather than `python`.

PEP 394 also notes:

> If the python command is installed, it should invoke the same version of Python as the python2 command (however, note that some distributions have already chosen to have python implement the python3 command)

So, in the wild, `python` might map to either `python2` or `python3`. Perhaps the linux client installer should allow for either possibility and be a bit more informative with the "python not installed" abort message.

**Comment by mazen160** [comment]
Hi @rgayler 

Thank you for reporting the issue.
I'm adding an addition to fix the issue.

Great work on researching I have to say:)

I'm passing notes to the support team to update docs.

protonvpn-cli does not rely on a specific Python version. I have made sure that the Python code invoked supports both Python2 and Python3. If you have any of the versions, it will be fine then.

I will update the ticket when I push the fix.

Thanks again!
Mazin

**Comment by rgayler** [comment]
My pleasure. I try to be useful within the limits of all the stuff I don't
know.

**Comment by mazen160** [comment]
Thanks @rgayler 

The issue should be now fixed.
