### ISSUE TITLE
Error connecting to VPN

### ISSUE THREAD

**Issue by ace4dude** [ProtonVPN/protonvpn-cli#107]
I can't connect any more! It got connected all the time in last a couple months up till today. Now it always returns `Error connecting to VPN`
Here's the log: 

[protonvpn-cli-logs-vxY2eVmP.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2133590/protonvpn-cli-logs-vxY2eVmP.txt)

**Comment by Rafficer** [comment]
Are you by any chance located in china?

**Comment by ace4dude** [comment]
@Rafficer Yes.

**Comment by Rafficer** [comment]
That's the problem. It looks like China is cracking down on ProtonVPN completely. Check https://reddit.com/r/protonvpn, there are some posts about it on there.

**Comment by ace4dude** [comment]
Oh sh*t. The access to protonvpn website was blocked long time ago, but access to ProtonMail is still good. I guess I need to get back to the backup proxy method.
