### ISSUE TITLE
tagged release  ?

### ISSUE THREAD

**Issue by Devil505** [ProtonVPN/protonvpn-cli#109]
I've requested to Solus developers to package protonvpn-cli but they need an actual tagged release.

https://dev.solus-project.com/T6682

**Comment by mazen160** [comment]
Hi @Devil505 

Thank you for checking and reporting to Solus.
It's on the plan within this month. Please expect an update on the upcoming days. We're focusing on this update to release more new features, then we will start on versioning part. 

Best,
Mazin

**Comment by mazen160** [comment]
Hi @Devil505 

Done!

Please let us know if there are anything you would like to be improved.

Best,
Mazin
