### ISSUE TITLE
Exclude country option

### ISSUE THREAD

**Issue by gerkus2** [ProtonVPN/protonvpn-cli#115]
Hello,

It would be great to have an option to connect to the fastest server available, excluding a given country. By starting with -f option alone, I could end up with a server located in my town :-)
I understand that I could also choose a specific country / server to connect, which would bypass this problem. But this way, I'm loosing the benefit of -f (choosing the fastest / least loaded location available).

Regards

**Comment by mazen160** [comment]
Hi @gerkus2 

This would be a very specific input. It's easy to develop of course, but it would make UX difficult.

I understand how you enter into this loop, there is a good option: `-cc` which is almost the same as `-f`.
You can choose the fastest VPN server in any country. It does the same calculations, just on a country wise:)

Thanks for suggesting this feature, and please feel free to let us know whever you have anything we can help with:)


Best regards,
Mazin

**Comment by elichai** [comment]
@mazen160 is this available in the android version too?

I want to get the fastest server that is *outside* my country (i.e exclude a country from the search)

Thanks!

**Comment by xilopaint** [comment]
@elichai this is not available in any version of ProtonVPN.
