### ISSUE TITLE
Add -sc flag to automatically select a secure core server

### ISSUE THREAD

**Issue by CodeMichael** [ProtonVPN/protonvpn-cli#116]
it would be nice to have new flag called "-sc" or similar, that would automatically select a secure core server.  This functionality would be similar to the -p2p flag.

Arguably this flag should not select the "fastest" SC server, but should chose entirely randomly for maximum security.  Or possibly allow for both options based on user preference (--fast-sc, --random-sc).

**Comment by mazen160** [comment]
Hi Michael,

Thanks for the detailed concept!

I have added it to the roadmap. It should be done soon. I expect it to be ready on either this or next month update.

Best,
Mazin

**Comment by mazen160** [comment]
Done!
