### ISSUE TITLE
Killswitch and localhost

### ISSUE THREAD

**Issue by Tamaranch** [ProtonVPN/protonvpn-cli#117]
Hi,
I have no access to localhost when Killswitch is enabled. Sorry if it is not a bug but a configuration that I missed.

**Comment by mazen160** [comment]
Hi 

This is related to the Killswitch pushed yesterday. localhost is blocked. I'm not sure about allowing localhost; it would extend an attack surface for DNS rebinding attacks for example, but it's still an essential part. Probably there will be an option to allow/block localhost access. There will be work on this part.

For now, you can access localhost by doing the following:

```bash
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
```
This will whitelist the loopback interface.

Let's keep this ticket open until a change is done.

**Comment by mazen160** [comment]
Hi @Tamaranch

Just letting you know that the fix for killswitch will allow acess to the loopback without special configurations. 

I will be closing the ticket. Thanks for posting the issue!

Best,
Mazin
