### ISSUE TITLE
Error when connecting to a Secure Core

### ISSUE THREAD

**Issue by azastrael** [ProtonVPN/protonvpn-cli#118]
Hi!

So first of all thanks to you all for the great work on the last version of the CLI! Everything works perfectly when trying to connect to a server except when it is a Secure Core one, where I get the following logs:
```
Connecting...
[$] Connected!
[#] New IP: 185.94.189.190
iptables v1.6.2: unknown protocol "185.159.156.15

tun0" specified
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.2: unknown protocol "185.159.156.15

tun0" specified
Try `iptables -h' or 'iptables --help' for more information.
```

Thank you!

**Comment by lucasrca** [comment]
Same problem here.

It seems that some iptables command is passing wrong values.

**Comment by mazen160** [comment]
Hi @azastrael 

Thanks for reporting this issue, and glad that you like the work going with protonvpn-cli!! :)

This is a severe bug, I will work on it today. It was not caught during my QA unfortunately. 

Best,
Mazin

**Comment by neontoaster** [comment]
Hey, I just opened a pull request (#128) which provides a simple fix for this.
I also just wanted to say that you're doing awesome work with this tool! It's a lot simpler than having to use openvpn and setting the firewall rules each time manually, much appreciated.

**Comment by mazen160** [comment]
Hi @azastrael 

The bug is now fixed. Killswitch will be activated soon once everything is tested across more platforms. 

Best,
Mazin
