### ISSUE TITLE
--init does not need root access

### ISSUE THREAD

**Issue by meownoid** [ProtonVPN/protonvpn-cli#120]

**Comment by Rafficer** [comment]
It does, for me.

https://i.imgur.com/6x0uHqe.png

**Comment by meownoid** [comment]
Yeah, it is required, but it isn't needed. This is what this issue about.

**Comment by Rafficer** [comment]
This is true if you initialize it for the first time (with a bit of rewriting, in the current state this wouldn't work as well), but upon re-initialization you would run into errors as the user wouldn't have the permissions to access `~/.protonvpn-cli` and therefore can't delete it.

**Comment by meownoid** [comment]
So, this is another bug then. All the contents of user home directory should be owned by him.

**Comment by Rafficer** [comment]
This is for security, as openvpn needs a plaintext file that contains the username and password. It's owned by root so your credentials are as secure as root.

**Comment by mazen160** [comment]
Hi @meownoid 

Exactly as Rafficer said, this is made for security purposes. Please find a longer discussion regarding this here: https://github.com/ProtonVPN/protonvpn-cli/issues/57

Best regards,
Mazin
