### ISSUE TITLE
Can't connect to the VPNs

### ISSUE THREAD

**Issue by flavienbonvin** [ProtonVPN/protonvpn-cli#13]
If I directly use the "protonvpn-cli.sh" from the git folder or the file located in "/usr/local/bin" I can't connect to any server with either the -connect (tested with tcp and upd protocol) and the -fastest-connect commands. I have a the following message: 

> Connecting...
> [!] Error connecting to VPN.
> Disconnecting...

**OS**: Solus x86_64
**OpenVPN**: 2.4.5
**sysctl**: 3.3.12
**python**: 3.6.4
**Dialog**: 1.3-20170131

**Comment by NodokaMurmevent** [comment]
same problem for me 
**OS :** Manjaro
**OpenVPN:** 2.4.5
**sysctl sysctl de procps-ng** 3.3.12
**Python:** 3.6.4
**Version:** 1.3-20171209

Log : 
```
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5539, in <module>
TypeError: '<=' not supported between instances of 'int' and 'str'
Connecting...
[!] Error connecting to VPN.
Disconnecting...
```

**Comment by bhuron** [comment]
Same problem here, both on my Fedora desktop and Raspbian.

`Connecting...
[!] Error connecting to VPN.
`

**OS**: Fedora 27/Raspbian
**OpenVPN**: 2.4.5
**sysctl**: 3.3.10
**python**: 3.6.4
**dialog**: 1.3-20171209

**Comment by sotpapathe** [comment]
I am also unable to connect. By removing the --daemon flag from openvpn, I get the following error:
`AUTH: Received control message: AUTH_FAILED`
on all servers I've tried so far. I have also tried downloading a config file manually and running
`sudo openvpn --config ~/Downloads/es.protonvpn.com.udp1194.ovpn --auth-user-pass ~/.protonvpn-cli/protonvpn_openvpn_credentials --auth-nocache`
but I got the same results. I even tried giving the username and password by hand but that didn't work either. When I use network-manager to setup the VPN everything works as expected. I am also experiencing similar problems on Solus but did not have time to do further testing on it.

**OS:** Ubuntu 16.04
**OpenVPN:** 2.3.10
**sysctl:** 3.3.10
**python:** 2.7.12
**dialog:** 1.3-20160209
**wget:** 1.17.1

**Comment by Rafficer** [comment]
If you do `sudo cat ~/.protonvpn-cli/protonvpn_openvpn_credentials` does it show your correct username and password?

**Comment by bhuron** [comment]
@Rafficer No. The ~ resolves to my HOME directory (not root's) and there is no .protonvpn-cli directory in there.

**Comment by Rafficer** [comment]
Yes, ~ should resolve to home. Did you install it properly? There should be a .protonvpn-cli directory in your home directory...

**Comment by xilopaint** [comment]
Do you guys have `/etc/openvpn/update-resolv-conf`?

**Comment by flavienbonvin** [comment]
@Rafficer After installing the tool I don't have a folder in
`~/.protonvpn-.-cli/protonvpn_openvpn_credentials`
@xilopaint no file in `/etc/openvpn/update-resolv-conf`

I'm on Solus 3.99

**Comment by bhuron** [comment]
@flavienbonvin If I read the script correctly, the folder is supposed to be in /root (you run the script as root). And it is, at least in my case.

**Comment by xilopaint** [comment]
> @Rafficer After installing the tool I don't have a folder in
> `~/.protonvpn-.-cli/protonvpn_openvpn_credentials`

The folder is `~/.protonvpn-cli` and not `~/.protonvpn-.-cli`. Just to make sure you're aware.

> @xilopaint no file in /etc/openvpn/update-resolv-conf

You can try the solution in #1. If it doesn't work for you, just revert back the changes.

**Comment by flavienbonvin** [comment]
I did some tests and found some interesting things. I always used the .sh file that I downloaded from github to do my testing (instead of the file installed by the program in /bin/local/usr/

If I change everything path in the init_cli() function by the absolute path of my machine everything works (I changed path from ~/.protonvpn-cli/ by /home/fbonvin/protonvpn-cli) and it worked, the folder is created and the files inside (protonvpn_openvpn_credentials and protonvpn_tier) are created.

Once the init done I had to do [this trick](https://github.com/ProtonVPN/protonvpn-cli/issues/1) (thanks @xilopaint) to be able to connect to any VPN. Once the file is created and chowd I can connect without any problem.

**Comment by bhuron** [comment]
@flavienbonvin Apparently, the script is broken because it makes the assumption that $HOME is still set to the home directory of the invoking user when running sudo (this is the case on Ubuntu by default but not on other systems). To fix this you don't have to touch the script, just pass the environment variable to sudo `sudo HOME=/home/fbonvin pronvpn-cli -init`

**Comment by flavienbonvin** [comment]
@bhuron this worked! But it should be handled by the program automatically in my opinion

**Comment by mazen160** [comment]
Hi all,

Just letting you know that I'm working on a fix regarding why protonvpn-cli is not working on certain distros. 

Thanks!

**Comment by mazen160** [comment]
I made an update on `update-resolv-conf`. Now the tool automatically downloads and installs update-resolv-conf if it's not installed.
This should fix the majority of "error connecting to VPN"

**Comment by mazen160** [comment]
For the `$HOME` related issue.
This is an expected behaviour, here is the idea:

If userA made a protonvpn-cli profile with
`sudo protonvpn-cli -init`
then the `$HOME` value will be `/home/userA` (in normal cases).

But when the user tries to run protonvpn-cli in `su` as the following:
```
$ sudo su

$ protonvpn-cli -c
```
protonvpn-cli assumes then that the user's profile is located at `/root/`, not `/home/userA`

This is a normal behavoiur with user-mangement. If you have multiple users on the same box, this approach isolate credentials. Also, if you try to run something like firefox for example, you will replicate the exact behaviour.

If you want to confirm this, you can do:

```
sudo echo $HOME 


sudo su
echo $HOME
```

Both should print a different value.

**Comment by bhuron** [comment]
@mazen160 

> If userA made a protonvpn-cli profile with
> sudo protonvpn-cli -init
> then the $HOME value will be /home/userA (in normal cases).

No, only on Ubuntu (which by default acts as if the -H option is given to sudo). On other distros (like Debian and Fedora), when running sudo, $HOME is set to to the home directory of the _target_ user (usually root), not the invoking user.

> If you want to confirm this, you can do:
> 
> sudo echo $HOME 
> 
> sudo su
> echo $HOME

This is not a good example. Here $HOME is expanded by the shell before sudo is invoked. Here is a better one:

`sudo sh -c 'echo $HOME'`

On my Debian and Fedora systems, the output is `/root`. On my Ubuntu system, it's `/home/benoit`. Meaning when protonvpn-cli is intialized on non-Ubuntu systems with sudo, it always puts the user's profile in /root (and the owner of these files is the invoking user). So, multiple users can't have different credentials.

**Comment by mazen160** [comment]
@bhuron 
Thanks for the detailed response. Do you have any idea on changing protonvpn-cli to allow multiple users in systems other than Ubuntu?

I don't have any ideas in mind that can improve this part without having the code written in a wrong way.

**Comment by bhuron** [comment]
@mazen160 Instead of using ~ in the script, maybe define a variable with the invoking user home directory and use it instead.
`USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)` 

You can also check if SUDO_USER is set or not. If it is not set, it means the program was inloked without sudo. In that case, use `whoami` instead of SUDO_USER to get the real user.
``[ $SUDO_USER ] && user=$SUDO_USER || user=`whoami` ``

Source https://stackoverflow.com/questions/7358611/get-users-home-directory-when-they-run-a-script-as-root#7359006

**Comment by NodokaMurmevent** [comment]
Thanks for the update everything work for me now.

**Comment by mazen160** [comment]
@bhuron 
I have added an update based on your input.
Commit: https://github.com/ProtonVPN/protonvpn-cli/commit/8516c0371bbb1d5f26b20ca418712df9b3cb6e3f

This should add support multiple user usage of protonvpn-cli in the same system, in platforms other than Ubuntu. 

Let me know if there is a problem on it, and I will be fixing it.

Thanks again!

**Comment by mazen160** [comment]
I will close the ticket for now since all the reported issues were fixed, if there is any issues, please feel free to re-open the ticket or submit a new issue.

Thanks everyone

**Comment by xilopaint** [comment]
I have a DNS issue in macOS, @mazen160. Please, DM me when you can talk.

**Comment by mazen160** [comment]
@xilopaint Will do now :+1:
