### ISSUE TITLE
[FEATURE REQUEST] Split tunnel support

### ISSUE THREAD

**Issue by DidierLmn** [ProtonVPN/protonvpn-cli#130]
Any plans to add the ability to easily allow split-tunnels through the cli? 
Maybe even an option to force only certain users/processes through the VPN?

**Comment by mazen160** [comment]
Hi @DidierLmn 

Thanks for the feature request!

Unfortuntelay, setting up split tunnels using protonvpn-cli is out of the scope of the project. You can customize it via downloading openvpn configs and add the rules in configs manually.  

Also, for process running, please expect an update regarding it based on your feature request ;) 


Thanks again!

Best,
Mazin
