### ISSUE TITLE
connecting issue:

### ISSUE THREAD

**Issue by avaporinTheWind** [ProtonVPN/protonvpn-cli#133]
after entering this command:
sudo protonvpn-cli -connect

Here is the error message output i am receiving after the attempting to connect to the server.
Not being able to manage IPv6 by protonvpn-cli might cause issues in leaking the system's IPv6 address. 16.04

[protonvpn_logfile.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2387080/protonvpn_logfile.txt)

Any help is greatly appreciated!
"thank you!"

**Comment by xilopaint** [comment]
`Sun Sep 16 16:49:14 2018 us=311293 AUTH: Received control message: AUTH_FAILED`

You likely used wrong credentials. Please, reinitialise your profile with `sudo pvpn --init` and make sure to use the right ProtonVPN OpenVPN credentials.

Just log in to the ProtonVPN website with your ProtonVPN credentials. After that you will find your OpenVPN credentials by clicking on Account.

**Comment by avaporinTheWind** [comment]
Thank you for the help!

after updating the username and pw, i received the following output:

[protonvpn_log2.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2387096/protonvpn_log2.txt)

:+1:

**Comment by xilopaint** [comment]
It still shows the AUTH_FAILED error.

Are you sure you got the OpenVPN credentials from the ProtonVPN website?

![vpn_dashboard_account](https://user-images.githubusercontent.com/11052366/45602053-5f2d6b80-b9ed-11e8-9985-fc36242bf7fd.jpg)

**Comment by avaporinTheWind** [comment]
yes.

**Comment by xilopaint** [comment]
It's very weird.

Please, uninstall the CLI by entering `sudo pvpn --uninstall` and download it from https://github.com/xilopaint/protonvpn-cli/tree/bug/fix-redirection. Install and initialise your profile again and post the output for `sudo pvpn -f`.

**Comment by avaporinTheWind** [comment]
Fetching ProtonVPN servers...
Connecting...
[$] Connected!
[#] New IP: 209.58.147.210

**Comment by xilopaint** [comment]
So it fixed the issue. Could you uninstall this version, and reinstall and test the official version again? I guess the issue was fixed with the uninstallation and re-installation and not by the differences between the versions. We need to know if the official version is working for you with the right credentials.

**Comment by avaporinTheWind** [comment]
Fetching ProtonVPN servers...
Connecting...
[$] Connected!

**Comment by xilopaint** [comment]
Awesome, thank you. If everything is working fine to you now, please close the issue.

**Comment by avaporinTheWind** [comment]
xilopaint, thank you for your help sir

**Comment by xilopaint** [comment]
> xilopaint, thank you for your help sir

You're welcome. Please, close the issue if everything is ok.
