### ISSUE TITLE
connecting issue

### ISSUE THREAD

**Issue by avaporinTheWind** [ProtonVPN/protonvpn-cli#134]
Hello, after entering initializing the vpn, connecting was unsucessful.  I recieved this error: 

[protonvpn_conn_log1.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2390435/protonvpn_conn_log1.txt)

thank you for your help (in advance)

**Comment by xilopaint** [comment]
You have the same issue you reported in #133. Bad ProtonVPN OpenVPN credentials.

**Comment by avaporinTheWind** [comment]
login creditials were recently re initialized.

**Comment by xilopaint** [comment]
> login creditials were recently re initialized.

What?

**Comment by avaporinTheWind** [comment]
i have recently reentered my login credentials properly.

**Comment by xilopaint** [comment]
You should be committing a mistake. Please repeat the steps you were told in #133.

**Comment by xilopaint** [comment]
@avaporinTheWind, do you still have this issue?

**Comment by avaporinTheWind** [comment]
i have very recently rolled back to ubuntu 14.04.5 lts. I will soon install protonvpn-cli again on this distro and am planning on moving forward from there. Thank you

**Comment by mazen160** [comment]
Hi @avaporinTheWind 
Please re-open the ticket if you're still facing this issue.

A quick way to debug it:
1) download an openvpn config from ProtonVPN website.
2) Locate protonvpn-cli directory
3) openvpn --config "example.ovpn" --auth-user-pass /path/to/protonvpn-cli-directory/protonvpn_openvpn_credentials
4) if it worked fine, then there is an issue in protonvpn-cli. If there was an error and the credentials are correct, then there should be on the backend.
