### ISSUE TITLE
OpenVPN UID/GID

### ISSUE THREAD

**Issue by Tamaranch** [ProtonVPN/protonvpn-cli#137]
I'm running Ubuntu 18.04, and it seems that in my case, `--group nobody` has to be replaced by `--group nogroup` at line [547](https://github.com/ProtonVPN/protonvpn-cli/blob/c6007d0fa4b603bfb5ff0c6af8dfda9cedc5865d/protonvpn-cli.sh#L547). Indeed, `nobody:nobody` is not recognized as non privileged user/group, but only `nobody:nogroup`.

NB: I have made this change locally and it works, that is, once connected, `ps -eo euser,egroup,comm | grep openvpn` gives "nobody nogroup openvpn". Otherwise, `openvpn` does not connect and it logs "failed to find GID for group nobody".

**Comment by Dvlnst** [comment]
It works also on Debian 9.4. Thank you.

**Comment by mazen160** [comment]
@Tamaranch @Dvlnst 

Can you please run the following command
`getent passwd nobody | cut -d: -f5`
and paste the output?

**Comment by Tamaranch** [comment]
It gives "nobody".

**Comment by mazen160** [comment]
@Tamaranch 
How about `id -gn nobody`?

**Comment by Tamaranch** [comment]
It's ok now, thanks!

**Comment by mazen160** [comment]
Awesome!! :)
