### ISSUE TITLE
Only TOR connects on Fedora installation

### ISSUE THREAD

**Issue by KinshipCourier** [ProtonVPN/protonvpn-cli#140]
I have run into an issue with the program being unable to connect to any VPN, except TOR on my Fedora 28 workstation. I have tried Free, Plus, different countries and P2P, but nothing except TOR connects. I elect "yes" when questioned about resolvconf installing, but it doesn't seem to be able to resolve the VPN addresses. When I elect "no" the program does not install.

The ProtonVPN-CLI program is updated and at v1.1.1.

I just installed over Ubuntu, which worked perfectly.

**Comment by KinshipCourier** [comment]
I've upgraded to the 29 pre-release and there's been no change.

**Comment by xilopaint** [comment]
Have you tried to connect with OpenVPN directly?

**Comment by KinshipCourier** [comment]
The output is just the: `[!] Error connecting to VPN.`, however, once it showed the error that it couldn't manage IPV6, but that was only one time if memory serves.

OpenVPN connects directly with the configuration files. I tried the Country Server for USA and specific servers in the USA. Both worked correctly.

**Comment by xilopaint** [comment]
Please, use `sudo PROTONVPN_CLI_LOG=true pvpn -f` and provide logs.

**Comment by KinshipCourier** [comment]
The logs are pretty long, so I put them on [Firefox Send,](https://send.firefox.com/download/f3769ebd69/#oLc_Z7VK4QDYjHBBX9bMhQ) unless you want them here for posterity or something. I can't see any obvious failures in the log.

**Comment by KinshipCourier** [comment]
I have been trying the program periodically to see if there were updates or any changes to my system. I was just able to successfully connect to two servers in US-IL#6 and US-IL#106 over UDP. I disconnected and reconnected with logging enabled to see if that would help in any way. They are [Here](https://send.firefox.com/download/a15f908d7c/#5ilCKzmptNKTYuUI9AGuyQ).

I attempted the program because the server connection from Network Manager kept failing. Strange.

**Comment by KinshipCourier** [comment]
I've been consistently able to connect to any server using the program, however I do not know what changed. Perhaps Fedora changed something. I'm going to go ahead and close the issue until there's reason to reopen.

**Comment by KinshipCourier** [comment]
This has reared it's ugly head again, but there's a new discovery. When I tether from my phone (over LTE) over USB, I can connect to servers, yet when on WiFi (Comcast) I cannot. This occurs only on Fedora however and seems to rule out the ISP. I've tried UDP and TCP connections. Here are new logs if anyone can use them.

[connection_logs.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2632516/connection_logs.txt)

**Comment by mazen160** [comment]
Hi @KinshipCourier !
I just read the logs attached. Probably there is an issue on the ISP (it happens a lot  ISPs <3 network restrictions :) )

There is still the issue on `Unknown interface 'tun0': No such device` although it was opened successfully. Maybe you can update and re-initialize the profile. Then have run as root set to true on the profile initialization. It should be fixing the issue since there is some client-side issues on your environment that disallows openvpn from running as "nobody" probably.


Thanks,
Mazin

**Comment by KinshipCourier** [comment]
Howdy, @mazen160! I hope your holidays went well.

I'm in a bind and I hate to bring up an old issue. I'm on Fedora 29 and experiencing the same issue as before. In truth, it never fully went away; I've been flitting between Debian and Fedora distros, but have settled in with Fedora

 When using `pvpn -tor` the connection is successful 100% of the time. I wonder what makes the TOR server special in this context.

[TOR-Connection.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2948301/TOR-Connection.txt)

When connecting to a random server either automatically using `pvpn -r` or manually, the logs usually look differently.

[Random-Connection.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2948303/Random-Connection.txt)

Both of these connection attempts were made with the profile initialized with not downgrading the privileges.

###

The following logs are from a reinitialization of the profile, selecting yes for privilege downgrade.


[TOR-Connection-Non_root.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2948308/TOR-Connection-Non_root.txt)

[Random-Connection-Non_root.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2948309/Random-Connection-Non_root.txt)

###

I have used this [Openresolv](https://github.com/rsmarples/openresolv) package that seems to help the connection complete, but it only works once and has to be recompiled and reinstalled each time I reconnect with protonvpn-cli. When I use it, I do see the /etc/resolv.conf file actually gets updated with ProtonVPN - DNS Server.

With all that being said, do you have any suggestions for me to try?

**Comment by KinshipCourier** [comment]
I just reinstalled POP_OS! 18.10, installed openresolv and all was well. I disconnected to test the reconnection issue and it looks like I'm running into #138 now. Reverting back to configuration files for the time being.

**Comment by xilopaint** [comment]
> I disconnected to test the reconnection issue and it looks like I'm running into #138 now. Reverting back to configuration files for the time being.

Please, reinitialise your profile by using sudo pvpn --init and choose `N` to `Decrease OpenVPN privileges`.

**Comment by KinshipCourier** [comment]
Hey, @xilopaint. Thank you for responding!

I've still got 18.10 installed and, I'm embarrased to say, that I did what you asked when I installed this morning, which yielded no results. However, I wish I would have gotten logs, because I just reinitialized the profile again and, after 30 random connects, it's 100% successful. I know I'm not crazy due to all the expletives I yelled at my laptop, I just wish I had gotten logs for you. It always seems to die and closes the tun0 connection after hanging for a while.

I did uninstall openresolv and reinstalled resolvconf; both work flawlessly.

As for Fedora, I'm at a total loss.

**Comment by xilopaint** [comment]
So is everything working smoothly now?

**Comment by KinshipCourier** [comment]
@xilopaint 

I've been trying new connections all throughout the day and I've only had a single failure, but it's out of 75 connections or so. Since my problem is sporadic on Ubuntu (currently..fixed?) and persistent on Fedora, I'll just stick with Ubuntu for the time being. I'm sorry to have bothered you without anything concrete.

I still wonder why the TOR server connects every time, without fail, even when the others can't. Does it handle DNS differently than the others?

**Comment by xilopaint** [comment]
> I still wonder why the TOR server connects every time, without fail, even when the others can't. Does it handle DNS differently than the others?

I don't know this part of the codebase as my plan doesn't give me access to the TOR servers. I'm sorry.
