### ISSUE TITLE
Cannot connect to vpn. "There is an internet connection issue." error every time.

### ISSUE THREAD

**Issue by BlueRorqual** [ProtonVPN/protonvpn-cli#141]
I'm running ubuntu 18.04.1 LTS, using the latest version of protonvpn-cli and I cannot connect with protonvpn-cli.

- "[!] Error: There is an internet connection issue." error thrown every time.

- connecting with ovpn config files does work, but connecting via cli does not.

- it seems like dns resolution isn't working for some reason with pvpn, but I could, of course, be mistaken.

Thank you in advance.

**Comment by mazen160** [comment]
Hi @BlueRorqual 

Thanks for reporting the issue. Can you please re-initialize your profile and use custom DNS as `1.1.1.1`. If it worked then there might be a DNS issue in pvpn. However, this is the first time to receive this type of issues for months. We haven't pushed updates regarding it, so I would assume it's machine/network issue mostly.

Best regards,
Mazin

**Comment by BlueRorqual** [comment]
Thank you for your response. I tried that and it still doesn't work. I'll reset my network settings and try.

**Comment by unbranched** [comment]
Suddenly in the last two days I receive the same error, it's the first time it  happens.
I'm on Fedora 28 x64, already tried to reinitialize it, even the `sudo pvpn --update` fails.
@BlueRorqual did you fix it?

**Comment by wis** [comment]
I shouldn't have had this issue for months with this simple cause and fix, I fixed it today exactly as @unbranched did.
should number of retries be configurable?
