### ISSUE TITLE
Feature request make this into a Desktop GUI for all Linux OS's

### ISSUE THREAD

**Issue by phd21** [ProtonVPN/protonvpn-cli#142]
HI protonvpn-cli developers, mazen160?

Thank you for creating this very nice Linux client for ProtonVPN. It works well from the console terminal.

I just installed Linux KDE Neon 5.14 based on Ubuntu 18.04 Bionic and it had trouble with permissions when using the one line "git clone" command; it made the folder and the script file root user access only. This worked perfectly on Ubuntu 16.04 Xenial (Linux Mint). So, I had to run the commands separately giving permissions first, then it ran. Then, I noticed the "wget" command, so I tried that and it seemed to work fine even though I already had it installed.

I really like the one suggestion about updating the Network Manager so that it is easy to see the VPN connections and their status.

Another great option would be to create a desktop GUI front-end for this that works. I tried the "protonvpn.py" (ProtonVPN-GTK) that another user created but it did not work on my system. After speaking with that developer, I did some KDE Settings for GTK desktop tweaking, I did get it up and running from the console terminal.

I help out a lot on the Linux Mint forums and I recommend the ProtonVPN and now your Linux Client. Before, I have just been telling people to import the individual (openvpn, .ovpn) servers into the Network Manager which does work. 

While helping another user who chose to go with "vpn.ac" rather than ProtonVPN, I had a chance to test their Linux Client and it is pretty nice and clean and works very similar to your client only it has a desktop Gui app that you might want to check out and perhaps you can use that as a template for creating a desktop GUI for this? I like that it has its own system tray panel icon showing connected or not connected with right-click options. Here is a link to their archive file and they also provide a deb installer file. It will come up even without an account so that you can see.
https://vpn.ac/beta/vpn.ac-linux-beta-1.2.tar.gz
[](https://vpn.ac/beta/vpn.ac-linux-beta-1.2.tar.gz)

Best regards,
Phil (phd21)
phd21mint@gmail.com

**Comment by xilopaint** [comment]
Creating a GUI app is not a feature request but a whole new project. This project is meant to develop a CLI. You can address your request to contact@protonvpn.com.

Regarding the installation issue I'm not sure if I got the problem. Haven't you succeed to install using sudo?

`$ sudo bash -c "git clone https://github.com/ProtonVPN/protonvpn-cli.git && ./protonvpn-cli/protonvpn-cli.sh --install"`

**Comment by mazen160** [comment]
Hi @phd21 

Thank you very much for your detailed request. As @xilopaint explained, this would be an actual full project. I have forwarded the request to the team for review.

The new PR pushed today acts as a great semi-GUI to pvpn. Please check the new pvpn -m.


All the best!

Regards,
Mazin

**Comment by elig0n** [comment]
I've started a simple, basic, tray icon utility in wxPython to serve as a sort of wrapper around `pvpn`.
It currently features showing the connection status as a balloon tip on tray mouse-over, connect to fastest/disconnect toggle menu option and showing the connection status represented as colorful or gray-scale icon for on/off accordingly. I might add further options later on but anyone is welcome to collaborate and extend it.

Find it here: https://github.com/elig0n/protonvpn_tray
