### ISSUE TITLE
Unable to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by rishispeets** [ProtonVPN/protonvpn-cli#143]
## Problem

Installing with the following command throws an error on my Ubuntu 18.04 installation. Unfortunately it's a catch all error message. Any pointers on where to look for a fix? 

### Command
```
sudo bash -c "git clone https://github.com/ProtonVPN/protonvpn-cli.git && ./protonvpn-cli/protonvpn-cli.sh --install" 
```

### Error 

```
Cloning into 'protonvpn-cli'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 444 (delta 0), reused 4 (delta 0), pack-reused 440
Receiving objects: 100% (444/444), 101.06 KiB | 184.00 KiB/s, done.
Resolving deltas: 100% (266/266), done.
[!] Error: There was an error in installing protonvpn-cli.
```

## Steps undertaken to fix

- Remove `/usr/local/bin/protonvpn-cli` and `/usr/bin/pvpn`.
- Manually check dependencies contained in installation script.
- Update dependencies.

**Comment by rishispeets** [comment]
Unfortunately not. I'm also not really familiar with bash scripting. It would seem like my error should be preceded by some other error. I tried running the script with `-x` to get additional debugging output but that yields nothing.

Looking at the script, I see there's an `error_counter`. In some places, like the `install_cli` function, it increments on an error without throwing an additional error message. _Should_ there be an error message accompanying the increment? Or are they silently caught somewhere?

I'll look into how can I add some additional logging output with bash. Any thoughts would of course be appreciated :).

**Comment by rishispeets** [comment]
Great! That did the trick. Thanks a lot! :+1:

**Comment by xilopaint** [comment]
@Tamaranch could you submit a pull request with the fix?

**Comment by Tamaranch** [comment]
Done… probably in a bad way at first. I hope it's correct now.

**Comment by xilopaint** [comment]
@Tamaranch can you close this issue since it has been fixed by e6cf905a2e61cf18c829f1d94146d4276f1f7267?

**Comment by Tamaranch** [comment]
@xilopaint I don't think I can close it, since I have not opened it. Perhaps @rishispeets ?

**Comment by mazen160** [comment]
Fixed!
