### ISSUE TITLE
install failure on mac os x - no openvpn found

### ISSUE THREAD

**Issue by sr-murthy** [ProtonVPN/protonvpn-cli#144]
I was unable to install the Proton VPN CLI because the shell script was unable to find an `openvpn` package on my Mac (OS X 10.13.6).

    [/path/to/protonvpn-cli]$ sudo ./protonvpn-cli.sh --install
    Password:
    [!] Error: openvpn is not installed. Install `openvpn` package to continue.

**Comment by xilopaint** [comment]
Just install OpenVPN with `brew install openvpn`.

**Comment by sr-murthy** [comment]
I don't understand. I installed `openvpn` on my Mac using `brew`:

	[2018-10-25 17:32:53 srm@~/Documents/sandeep/cst/protonvpn-cli]$ brew install openvpn
	==> Downloading https://homebrew.bintray.com/bottles/openvpn-2.4.6.high_sierra.bottle.tar.gz
	Already downloaded: /Users/srm/Library/Caches/Homebrew/downloads/de5d381f8eb64af72a02204132e44ce5babfce55d0de7852cd31e689798c13d8--openvpn-2.4.6.high_sierra.bottle.tar.gz
	==> Pouring openvpn-2.4.6.high_sierra.bottle.tar.gz
	==> Caveats
	To have launchd start openvpn now and restart at startup:
	  sudo brew services start openvpn
	==> Summary
	🍺  /usr/local/Cellar/openvpn/2.4.6: 83 files, 1.4MB

but running `sudo ./protonvpn-cli.sh --install` gives me an error:

    [!] Error: openvpn is not installed. Install `openvpn` package to continue.

**Comment by sr-murthy** [comment]
Ah, I forgot to add `/usr/local/Cellar/open` to the system path.

**Comment by sr-murthy** [comment]
Doesn't work. I get the same error. This is hopeless, and anyway I am not interested in using this tool.

**Comment by xilopaint** [comment]
It's weird, on my Mac Homebrew installed a symlink to openvpn binary at `/usr/local/sbin` so I didn't need to `/usr/local/Cellar` to system path.
