### ISSUE TITLE
Having a changelog when updating the application and a command that allow to display it

### ISSUE THREAD

**Issue by flavienbonvin** [ProtonVPN/protonvpn-cli#153]
It could be great to have the option let's say `pvpn --change` to know that the changelog between version is, it could either output the changelog for every version or only the last one (from version 1.1.1 to 1.1.2 for example). On top of that, when updating the application the changelog could be displayed to know what's new (I didn't know about the new menu because without going here or running `pvpn -h` there are no way of knowing wat's changed)

**Comment by mazen160** [comment]
Hi @flavienbonvin!

Thanks for your feature. This will be rolled out on next update. There will be more documentation on what was changed on releases next.

Best Regards,
Mazin
