### ISSUE TITLE
Writes root-owned files in ~$SUDO_USER/.protonvpn-cli/ when using sudo

### ISSUE THREAD

**Issue by sorsasampo** [ProtonVPN/protonvpn-cli#158]
`get_home()` function uses `$SUDO_USER` for figuring out the home directory. This points to the home directory of the user who invoked sudo. This causes the directory and files written to be owned by root, so they are unaccessible by the regular user. Writing unaccessible files to the user's home directory is not a good thing!

The files should be either written in home directory of the effective user, or owner and permissions set to `$SUDO_USER`, preferably the former.

**Comment by mazen160** [comment]
Hi @sorsasampo !

Thanks for your message.

This is intentionally made to protect user credentials while supporting multiple users per machine and separating different accounts per home directory.

**Comment by sorsasampo** [comment]
In that case, you really should set the ownership to `$SUDO_USER`. There is no excuse for writing unreadable files to user home directory, apart from laziness.

**Comment by mazen160** [comment]
@sorsasampo 
Nope, there is a reason for that. The point of assigning root reading to the file is that normal users should not be able to read VPN credentials. It's basically securing OpenVPN credentials by user-permissions.

```
$ cat ~/.protonvpn-cli/protonvpn_openvpn_credentials
cat: /home/X/.protonvpn-cli/protonvpn_openvpn_credentials: Permission denied
```

There was a longer discussion about this part in previous Issues.

Best,
Mazin

**Comment by sorsasampo** [comment]
What issue was this discussed in?

**If the user is not supposed to be able to read the files, then they should not be written in the user's home directory**. There is no excuse for doing that. You can namespace the directory elsewhere by including `$SUDO_USER` in the path, but seriously, please don't pollute user home with unreadable files!

**Comment by elig0n** [comment]
@mazen160  if a user inputs credentials then what's the point of preventing him access to it ? If the credentials configuration is supposed to be system-wide (set by an admin) then it should not be written to a `$USER` directory at all. A place like `/etc/protonmail/` would be better suited.
Also, `pvpn--status` doesn't work right without read permission for that directory, which is why I wrote this:

https://github.com/elig0n/protonvpn-cli/commit/bbea55b2b59b89b25cbd47c6d3b108eb6cc0ee81

**Comment by elig0n** [comment]
@mazen160  if a user inputs credentials then what's the point of preventing him access to it ? If the credentials configuration is supposed to be system-wide (set by an admin) then it should not be written to a `$USER` directory at all. A place like `/etc/protonmail/` would be better suited.
Also, `pvpn--status` doesn't work right without read permission for that directory.

**Comment by elig0n** [comment]
Temporary fix for sudoers that trust their users: https://github.com/elig0n/protonvpn-cli/commit/58de893b52f590077aebeafad2bf34e88aa4187c

**Comment by elig0n** [comment]
See https://github.com/elig0n/protonvpn-cli/commit/58de893b52f590077aebeafad2bf34e88aa4187c

**Comment by Tamaranch** [comment]
mazen160 is no longer in charge of this project, it is @kaplun now.
Concerning `pvpn--status`, this is due to a regression introduced by PR #178.

**Comment by sorsasampo** [comment]
@Tamaranch is this issue going to be reopened and fixed?

**Comment by Tamaranch** [comment]
I really don't know. I'd like, but I'm pessimistic: this project doesn't seem really maintained anymore.

**Comment by sorsasampo** [comment]
Oops, meant to ping @kaplun with the question.

**Comment by Rafficer** [comment]
Just going to jump in here to continue the discussion:

The point being that it's more likely that a user account is compromised than the root account as the majority of programs a regular user uses is run as his user. So if an attacker gets ahold of one process or the user executes malware with it's user account, that malware can't access your ProtonVPN credentials.

Putting the credentials somewhere else isn't feasible as it would entirely break the possibility of multiple users using the program with their own account.

**Comment by sorsasampo** [comment]
> Putting the credentials somewhere else isn't feasible as it would entirely break the possibility of multiple users using the program with their own ProtonVPN account.

That's simply not true. There's nothing that prevents protonvpn-cli from namespacing the paths with username elsewhere. If you want root-owned files, just don't put unaccessible files in user homes!

**Comment by Rafficer** [comment]
It's also not very nice to put user specific files outside of the home directory. It's simply a security feature.
Putting them elsewhere would also make them potentially accessible to other users, even when using encrypted home directories.

The main issue is that OpenVPN requires a plain-text file containing your username and password. If there would be a fix for that, this could be entirely omitted and even more security could be added.
