### ISSUE TITLE
Help command shouldn't need sudo

### ISSUE THREAD

**Issue by zack-baker** [ProtonVPN/protonvpn-cli#16]
I don't understand why the help command needs root access. As well, providing no arguments should display the help message, regardless of user access

**Comment by mazen160** [comment]
Hi @zack-baker 
Thanks for reporting this. I have made modifications to follow this
commit: https://github.com/ProtonVPN/protonvpn-cli/commit/d0ba2dfb16bb07428598e5d7b2ce216e92c33075

Please re-open the ticket if you feel it requires additional changes.

Thanks again!

Best,
Mazin
