### ISSUE TITLE
bypassing sudo?

### ISSUE THREAD

**Issue by k1nghat** [ProtonVPN/protonvpn-cli#162]
is it possible to not need sudo? maybe through the use of users and groups it can be done where you dont have to sudo everything?

**Comment by Rafficer** [comment]
This should help you:

https://www.oreilly.com/library/view/linux-security-cookbook/0596003919/ch05s04.html

Not using sudo at all doesn't really work as openvpn needs root privileges, but you can bypass the password authentication if your user is a sudoer.

**Comment by k1nghat** [comment]
> This should help you:
> 
> https://www.oreilly.com/library/view/linux-security-cookbook/0596003919/ch05s04.html
> 
> Not using sudo at all doesn't really work as openvpn needs root privileges, but you can bypass the password authentication if your user is a sudoer.

can it be done for just protonvpn-cli though?

**Comment by Rafficer** [comment]
Yes, as described, you are specifying the program to exclude.

**Comment by mazen160** [comment]
Yes, exactly as @Rafficer said, it should be done by the user if needed.
