### ISSUE TITLE
Make protonVPN/openVPN log to syslog.

### ISSUE THREAD

**Issue by joelstahre** [ProtonVPN/protonvpn-cli#165]
Is it possible to make protonVPN to send logs to syslog?
If not, can it be implemented!

**Comment by mazen160** [comment]
Hi @joelstahre !

Yes, it should be possible to do so by sending OpenVPN logs directly to syslog. 

Or you can access logs at ~/.protonvpn-cli/connection_logs

If you modify the arguments at openvpn-connect on protonvpn-cli to add `--syslog`, you should be able to do so!

Best Regards,
Mazin
