### ISSUE TITLE
Killswitch Ubuntu 16.04

### ISSUE THREAD

**Issue by natxyz** [ProtonVPN/protonvpn-cli#166]
Hey, just had to downgrade from Ubuntu 18.04 on which I use using protonvpn-cli with a systemd auto-restart script and kill switch working perfectly. Unfortunately I had some issues with conflicting hardware on 18.04 which has forced me go back to 16.04.

Just setting up protonvpn-cli now and noticed when I do --init, it doesn't ask me if I want to enable killswitch as it did when I ran --init on Ubuntu 18.04 - is there something I'm missing here?

I followed this instruction initially on 18.04 and doing it the same way on 16.04 now - https://blog.x86txt.com/protonvpn/security/2018/12/02/protonvpn-cli-as-systemd-service.html

**Comment by mazen160** [comment]
Hi @natxyz,

The killswitch is currently disabled due to some bugs that will be fixed soon.

Please expect an update soon regarding the killswitch!

Best Regards,
Mazin

**Comment by YarmoM** [comment]
We are over 6 months later, any update on the killswitch yet?
