### ISSUE TITLE
Issues in managing IPv6 in the system

### ISSUE THREAD

**Issue by cccaballero** [ProtonVPN/protonvpn-cli#168]
Hi, I have successfully connected the first time I run the client, but now I am not able to establish the connection any more, the error output is:

```
Connecting...
[!] Error connecting to VPN.
[!] There are issues in managing IPv6 in the system. Please test the system for the root cause.
Not being able to manage IPv6 by protonvpn-cli may leak the system's IPv6 address.
```
and the log: [connection_logs.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2724920/connection_logs.txt)

**Comment by xilopaint** [comment]
Could you check if IPv6 is enabled or disabled to you?

**Comment by mazen160** [comment]
Same as: https://github.com/ProtonVPN/protonvpn-cli/issues/167#issuecomment-455148781

Choosing n to `decreasing privileges` should fix this problem for your setup. Let us know if it worked!

**Comment by cccaballero** [comment]
Thanks guys, I got it working now, I just forgot to update the issue, the firewall was causing some weird behavior.
