### ISSUE TITLE
pvpn makes Ubuntu 18.04.1 unresponsive randomly (especially after lock)

### ISSUE THREAD

**Issue by 2lone2bone** [ProtonVPN/protonvpn-cli#171]
I have this really strange problem that I have never ever seen before. The problem is that when the pvpn disconnects it will take the whole connection down (I guess this is related to killswitch, which I don't know how to disable since it is not in the config file nor in the init wizard). This happens mostly after afk and automatic lock, however not every time (would say 50%).
What is the damnest thing is that OS does work normally just without internet but... If you try to sudo something the terminal hangs there forever after password... so basically I can't do anything. Ok lets try to shutdown/reboot then. Of course that doesn't work and the system will hang infinitely to the ubuntu screen and I have to hard shutdown my pc.

**Comment by 2lone2bone** [comment]
I just removed the pvpn and use openvpn which solved the issue.

**Comment by xilopaint** [comment]
> I guess this is related to killswitch, which I don't know how to disable since it is not in the config file nor in the init wizard

Killswitch is already disabled due to some bugs.
