### ISSUE TITLE
changes resolv.conf but never changes it back

### ISSUE THREAD

**Issue by estiens** [ProtonVPN/protonvpn-cli#175]
This makes changes to the DNS servers listed in resolv.conf, however, after running `pvpn -d`, the changes remain, resulting in DNS servers that can't be reached.

**Comment by xilopaint** [comment]
Do you get any error message?

**Comment by estiens** [comment]
I didn't get any error message....

But, I re-installed the CLI and now it works fine and changes `resolv.conf` on disconnect. Closing this for now.
