### ISSUE TITLE
Unable  to connect after disconnecting

### ISSUE THREAD

**Issue by dron1885** [ProtonVPN/protonvpn-cli#176]
I encounter a problem with protonvpn-cli.

Running `protonvpn-cli -f` first time everything works fine.
After some time if it's required to disable VPN `protonvpn-cli -d` still do what it should.

But next time I try to connect I get this:
```
Fetching ProtonVPN servers...
Connecting...
[!] Error connecting to VPN.
```
Rebooting is only way to connect to VPN again

System: Linux, 4.20.11-arch1-1-ARCH.

Logs : [connection_logs.txt](https://github.com/ProtonVPN/protonvpn-cli/files/2924924/connection_logs.txt)

**Comment by xilopaint** [comment]
Please, run `sudo PROTONVPN_CLI_LOG=true protonvpn-cli.sh -f` and provide logs.

**Comment by dron1885** [comment]
Updated first post.

**Comment by xilopaint** [comment]
You seem to be running into #138.

Please, reinitialise your profile by using `sudo pvpn --init` and choose `N` to `Decrease OpenVPN privileges`.

**Comment by dron1885** [comment]
Reinitializing helped. Don't know how I missed previous issue.

**Comment by xilopaint** [comment]
So is everything working fine now?

**Comment by dron1885** [comment]
Yes, it seems so. Thank you!

**Comment by xilopaint** [comment]
@dron1885 Nice! You can close the issue now.

@mazen160 what about we grep the log file to search occurrences of this issue and in positive cases use a warning to instruct the user to reinitialise his/her profile accordingly?
