### ISSUE TITLE
Unknown OID

### ISSUE THREAD

**Issue by cantab412** [ProtonVPN/protonvpn-cli#18]
When trying to connect, I get an error:

```
$sudo ./protonvpn-cli.sh -connect

[pick a server and protocol from the list]

[!] Error connecting to VPN.
sysctl: unknown oid 'net.ipv6.conf.all.disable_ipv6'
sysctl: unknown oid 'net.ipv6.conf.default.disable_ipv6'
```

Mac running 10.13.3 and Brew-installed utilities, if that helps at all.

**Comment by mazen160** [comment]
Hi @cantab412 
Thanks for reporting this. I have added an addition to better handle ipv6 errors.

A long-term goal is to include independent function for handling Ipv6.

**Comment by mazen160** [comment]
I made a ticket here: https://github.com/ProtonVPN/protonvpn-cli/issues/42
