### ISSUE TITLE
Is there a plan to make it work for OpenBSD

### ISSUE THREAD

**Issue by adamsteen** [ProtonVPN/protonvpn-cli#182]
Hi after seeing #164, I thought i would raise a specific issue for OpenBSD.

I attempted a `doas ./protonvpn-cli.sh --install` and installed packages as they were requested, but `iptables` was requested. OpenBSD does not support `iptables` but has `pf` see [pf(4)](https://man.openbsd.org/pf) and [PF - User's Guide](https://www.openbsd.org/faq/pf/index.html).

Are there any plans to support this?

**Comment by Tamaranch** [comment]
`iptables` is not actually a requirement (it does not appear in the documentation). It should have been commented, because its use is commented in the code. You can comment it yourself at line 54-59, and redo a `doas ./protonvpn-cli.sh --install`.

**Comment by adamsteen** [comment]
next problems were sha512sum and shasum don't exist on OpenBSD, so i had to use `sha512` and tweak the script.

should the `.protonvpn-cli` be install in root or the current users home dir?

see "add OpenBSD Support." #183

the script is not very verbose, a verbose mode would be great in understand what the script is trying to do.

**Comment by Tamaranch** [comment]
> should the `.protonvpn-cli` be install in root or the current users home dir?

See #159…

**Comment by adamsteen** [comment]
I am able to get it working, but i am not happy with it. see [adamsteen/protonvpn-cli](https://github.com/adamsteen/protonvpn-cli) use at your own risk.

**Comment by adamsteen** [comment]
Closing as I have t heard anything back from @ProtonVPN

**Comment by adamsteen** [comment]
Closing as I have t heard anything back from @ProtonVPN
