### ISSUE TITLE
configuration changed

### ISSUE THREAD

**Issue by zkzkzk2015** [ProtonVPN/protonvpn-cli#190]
I tried to connect to US server and UK server and it is working, but i am getting following info:
_Configuration changed (of linux-udp-qh_qQPwjLZU-Uzx2oXLq5Bl3eS-gjhYm7mxO5rCBzGMa7oLhNMfshPmpP9QWj7......)_
I am using ubuntu 18.04 LTS and protonvpn command-line tool 1.1.2

**Comment by xilopaint** [comment]
Please, post the entire log.

**Comment by zkzkzk2015** [comment]
Where do I find logs?

**Comment by xilopaint** [comment]
> Where do I find logs?

Run `sudo PROTONVPN_CLI_LOG=true pvpn -f`.

Where did you find that message?

**Comment by zkzkzk2015** [comment]
a) sudo PROTONVPN_CLI_LOG=true pvpn -f does connect me to a US server, but it does not create a log file.
b) message appears right after I type pvpn -c, right before I can choose between all the different servers.

**Comment by xilopaint** [comment]
> a) sudo PROTONVPN_CLI_LOG=true pvpn -f does connect me to a US server, but it does not create a log file.

Weird. It should output the path of the log file.

> b) message appears right after I type pvpn -c, right before I can choose between all the different servers.

So you can only see it for a second or so? I'm not aware of such message. Sorry.

**Comment by zkzkzk2015** [comment]
Yeah it shows up in the console, not in the logs. (logs are supposed to be created in my home directory, but it does not).

**Comment by xilopaint** [comment]
> (logs are supposed to be created in my home directory, but it does not)

They are created in a `.protonvpn-cli` folder in your home directory.

**Comment by zkzkzk2015** [comment]
Okay, I am really sorry. My bad. I had to be root to enter .protonvpn-cli even it is in my home folder.
logs only show data from today (problem occured two days ago), so it probably does not make sense to post it, I guess.

**Comment by xilopaint** [comment]
> logs only show data from today (problem occured two days ago), so it probably does not make sense to post it, I guess.

The log file shows data from your last attempt to connect to ProtonVPN.

**Comment by zkzkzk2015** [comment]
Thank you. I am closing this thread.
