### ISSUE TITLE
Adding blacklist option

### ISSUE THREAD

**Issue by gerardo-junior** [ProtonVPN/protonvpn-cli#198]
a good idea is to have an option in the app with blacklist option like [easylist](http://easylist.to) to block trakers and ad's on request like brave browser or ublock does

**Comment by Rafficer** [comment]
That would need to happen on a DNS level and the cli doesn't modify the DNS servers or monitors traffic.

The easiest solution would be to add the hosts you want to block to your /etc/hosts file accordingly.

**Comment by gerardo-junior** [comment]
where can i suggest for this to be proposed to protonvpn servers, not the cli?

**Comment by Rafficer** [comment]
Either https://protonmail.uservoice.com or directly to them via https://protonvpn.com/support-form

I personally think an optional DNS blocking server would be a great feature as well.
