### ISSUE TITLE
Clean up on Ctrl-C

### ISSUE THREAD

**Issue by sorsasampo** [ProtonVPN/protonvpn-cli#3]
The script should `trap` `SIGINT` and tear down the setup if connection has not been established yet.

Currently Ctrl-C can put your system into a disconnected state until you rerun with `-disconnect`.

**Comment by mazen160** [comment]
Hi @sorsasampo 

May you please elaborate on how does CTRL+C put the system into a disconnected state?

This should not happen as no changes are done to the system if no proven successful connection is established.

**Comment by sorsasampo** [comment]
If you run `watch -d1 dig google.com` in one terminal and `sudo bash -x protonvpn-cli.sh --connect` in another, you'll see that DNS starts failing at some point. If you Ctrl-C then, it stays that way.

Probably related to running `openvpn`, because the only thing that you run after that is `wget`.

I can't connect to ProtonVPN either, probably because `api.protonmail.ch` fails to resolve.

**Comment by mazen160** [comment]
Hi @sorsasampo

I have tested the issue today, and I can't reproduce the ticket. This has to be related to  either `openvpn` or your internet connection.

My testing didn't show any unexpected error or behaviour.

**Comment by sorsasampo** [comment]
> This has to be related to either openvpn or your internet connection.

I have no doubt that it's caused by the `openvpn` process that is launched in the background shortly before.

> Do you know why you can't connect to api.protonmail.ch? Maybe it's related to the internal VPN DNS resolver?

No idea. Something probably goes wrong with the `openvpn` call.

FWIW, connecting to ProtonVPN using imported `.ovpn` profile works with NetworkManager.

Running Debian Stretch / 9.4.

**Comment by mazen160** [comment]
We don't have control on this part, as we're following the right standard on making the `openvpn` call. As far as there is no notable issue, I believe this ticket should be closed for future reference.

**Comment by mazen160** [comment]
@sorsasampo Thanks again for reporting it.
