### ISSUE TITLE
v0.22 hangs/won't start

### ISSUE THREAD

**Issue by cantab412** [ProtonVPN/protonvpn-cli#40]
[edit: just realised this Git is for the CLI and not the app.  Don't file bugs before you've had coffee]

Hi - I downloaded the current update this morning and the app won't start.  

The icon appears in the dock and just sits there - the only option is to Force Quit.

On system start, the app launches and hangs.  This is the only entry in /var/log/system.log:

`com.apple.xpc.launchd[1] (ch.protonvpn.mac.25484[676]): Service exited due to signal: Terminated: 15 sent by Dock[350]`

Running the app directly from the command line gives this:

```
$ ./ProtonVPN
2018-03-26 07:35:32.491 ProtonVPN[968:25097] Successfully add login item.
^C
```

**Comment by mazen160** [comment]
Hi @cantab412 
No problem!:)

I will close the ticket, and I will forward this to MacOS team for checking.

**Comment by mazen160** [comment]
Hi @cantab412

Just letting you know that I passed it to our macOS developers, and they told me it's on their priority to fix this issue soon.

Thanks,
Mazin
