### ISSUE TITLE
Adding support for updating functinality

### ISSUE THREAD

**Issue by mazen160** [ProtonVPN/protonvpn-cli#41]
As discussed on https://github.com/ProtonVPN/protonvpn-cli/pull/39

Thanks @arderyp for the addition!

**Comment by mazen160** [comment]
Done!

**Comment by arderyp** [comment]
wow @mazen160, that was quick.  Looks good!  Definitely more robust than my attempt.

**Comment by mazen160** [comment]
@arderyp 
Thanks! Totally glad to help! :)
