### ISSUE TITLE
getent: command not found

### ISSUE THREAD

**Issue by cantab412** [ProtonVPN/protonvpn-cli#43]
When installing or running the latest version (just pulled this morning), I get the following errors when installing and running:

```
$ sudo ./protonvpn-cli.sh -init
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
Enter OpenVPN username: [Redacted]
Enter OpenVPN password: 
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found

[.] ProtonVPN Plans:
1) Free
2) Basic
3) Plus
4) Visionary
Enter Your ProtonVPN plan ID: 3
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
[*] Done.


$ sudo ./protonvpn-cli.sh -f
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
Fetching ProtonVPN Servers...
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 59: getent: command not found
Connecting...
./protonvpn-cli.sh: line 59: getent: command not found
./protonvpn-cli.sh: line 143: ip: command not found
[$] Connected!
[#] New IP: 185.159.158.50


$ sudo ./protonvpn-cli.sh -d
Disconnecting...
./protonvpn-cli.sh: line 59: getent: command not found
cat: /Users/cantab/.protonvpn-cli/.ipv6_address: No such file or directory
./protonvpn-cli.sh: line 174: ip: command not found
[!] There are issues in managing ipv6 in the system. Please test the system for the root cause.
Not able to manage ipv6 by protonvpn-cli might cause issues in leaking the system's ipv6 address.
[#] Disconnected.
[#] Current IP: [Redacted]

```

Running OSX 10.13.3
IP6 set to "Automatic" configuration
Bash v3.2

**Comment by mazen160** [comment]
Hi @cantab412 

The `getent` is a newly added dependency to allow multiple users of using pronvpn-cli.

Can you please try to install it on your machine?

If it worked, I will add it to dependencies.

Thanks,
Mazin

**Comment by cantab412** [comment]
Hi @mazen160 

Not trying to be difficult, but `getent` isn't something that seems to be readily available on OS X.  Brew doesn't have it, nor does anywhere else apparently.

There are lots of Google hits about it from several years ago, and comments about using `dscacheutil` instead [1]

Is there another method that could be used to achieve the getent functionality?  Keeping things as plain/out-of-the-box as possible will be important for "normal" users.

[1] https://apple.stackexchange.com/questions/44567/how-can-i-install-getent-on-snow-leopard

**Comment by mazen160** [comment]
Hi @cantab412 

Thank you again for reporting this issue. 

The addition was made initially to support multiple users in the same machine. I didn't want to break the functionality, and wanted to fix the issue for macOS users.

I have pushed a simple fix that seems to be fixing it. Please test it and let me know if you still encounter the same issue. The fix is to rely on `$HOME` if the output of `getent` is none.

Thanks,
Mazin

**Comment by cantab412** [comment]
@mazen160 - seems to be working now, thanks!

One error to report, though:

```
$ sudo ./protonvpn-cli.sh -f
Connecting...
./protonvpn-cli.sh: line 143: ip: command not found
[$] Connected!
[#] New IP: 185.159.158.51
```

**Comment by mazen160** [comment]
@cantab412 
This is related to macOS ipv6 management. It's on my todo too :)

Thanks!

Best,
Mazin

**Comment by mazen160** [comment]
the ipv6 management part have an open ticket at https://github.com/ProtonVPN/protonvpn-cli/issues/42

**Comment by xilopaint** [comment]
> @cantab412
> This is related to macOS ipv6 management. It's on my todo too :)

In any case the error should be suppressed as macCOS doesn't have a ip command.

**Comment by xilopaint** [comment]
@cantab412 do you use a public DNS server?

**Comment by cantab412** [comment]
@xilopaint Yes.  Usually from https://www.opennic.org/

**Comment by xilopaint** [comment]
> @xilopaint Yes. Usually from https://www.opennic.org/

Thank you for the confirmation. You should not be able to use ProtonVPN with a DHCP-assigned DNS at the moment. It's an issue with protonvpn-cli. I will open this issue now.
