### ISSUE TITLE
Error running -update

### ISSUE THREAD

**Issue by cantab412** [ProtonVPN/protonvpn-cli#45]
When running -update, I get the following error:

```
$ sudo ./protonvpn-cli.sh -update
[#] Checking for update.
./protonvpn-cli.sh: line 287: sha512sum: command not found
./protonvpn-cli.sh: line 293: sha512sum: command not found
[*] protonvpn-cli is up-to-date!
```
OSX 10.13.3

**Comment by ohdearaugustin** [comment]
nstall GNU coreutils package provided by MacPorts. Other package managers, like Fink, would work.

**Comment by cantab412** [comment]
@ohdearaugustin Should be listed as a dependency if a stock alternative can't be used.

OSX 10.13.3

**Comment by xilopaint** [comment]
We should try to write portable code as much as possible. So I would first seek for a portable alternative to `sha512sum`.

If there's no good alternative, `coreutils` can be installed with `brew install coreutils` and the binary should be linked:

`sudo ln -s /usr/local/bin/gsha512sum /usr/local/bin/sha512sum`.

If we stick with `sha512sum` I think the link should be handled by the script.

**Comment by cantab412** [comment]
@ohdearaugustin Using `brew` to install `coreutils`, `sha512sum` is installed as `gsha512sum`.

Brew users will have to add `/usr/local/opt/coreutils/libexec/gnubin/` to their path in order to use it natively.

**Comment by mazen160** [comment]
protonvpn-cli now checks if `sha512sum` or not. Also, this issue's url is  printed on screen for reference.

**Comment by cantab412** [comment]
@mazen160 -update seems to work with (g)sha512sum installed and linked per previous post.  I just downloaded the latest version with `git clone` so I'll have to wait to test until the next update is pushed.

```
$ sudo ./protonvpn-cli.sh -update
[#] Checking for update.
[*] protonvpn-cli is up-to-date!
```

**Comment by mazen160** [comment]
@cantab412 
Great!!
