### ISSUE TITLE
Command syntax for using -c ?

### ISSUE THREAD

**Issue by cantab412** [ProtonVPN/protonvpn-cli#48]
When trying to use `-c` to specify an endpoint, I get an error:

```
$ sudo ./protonvpn-cli.sh -c uk5 tcp
Fetching ProtonVPN Servers...
./protonvpn-cli.sh: line 405: ${2,,}: bad substitution
```
I have tried various formats including the #  in the server name as taken from the server list when running `-c` by itself, but keep getting the same error.

**Comment by cantab412** [comment]
```
$ sudo ./protonvpn-cli.sh -c JP#4 tcp
Password:
Fetching ProtonVPN Servers...
./protonvpn-cli.sh: line 405: ${2,,}: bad substitution
```

```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by ohdearaugustin** [comment]
when did you download the script?

**Comment by ohdearaugustin** [comment]
oh I see the problem the bash is to old. this command only work with bash version > 4.0

**Comment by Rafficer** [comment]
This might be a thing to add to the dependencies then

**Comment by njfox** [comment]
I was a little worried about this but I wasn’t sure how common bash < 4.0 is. What platform are you on?

**Comment by cantab412** [comment]
Correct - High Sierra 10.13.3.

I'll get Bash v4 set up tomorrow and test.

**Comment by njfox** [comment]
I’d rather change the case insensitive comparison method and have it work out of the box than add a dependency if it’s going to affect a lot of users. I’ll take a look later when I have some time

**Comment by xilopaint** [comment]
Any news on this @njfox ?

**Comment by xilopaint** [comment]
Any news on this @njfox ?

Btw, I also agree with this:

> I’d rather change the case insensitive comparison method and have it work out of the box than add a dependency if it’s going to affect a lot of users.

Could you submit a PR removing the case insensitive comparison?

**Comment by njfox** [comment]
I think the comparison should be case insensitive so people don't get an error if they type `UDP` or `us-ca#1` instead of `udp` and `US-CA#1`. Unfortunately the other ways I've seen to do this seem a lot messier and I don't have a MacOS device to test it. 

I will mess around with it and submit a PR when I can but someone else is welcome to do that PR if they have the time/interest

**Comment by mazen160** [comment]
Hi all,

I have pushed a backward compatibility change that should fix the issue. 

Please let me know if you're still facing the error or the functionality is not working properly.

Thanks,
Mazin

**Comment by cantab412** [comment]
@mazen160 Confirmed this is working now.

Installed coreutils from Brew.  Linked /usr/local/bin/gsha512sum to /usr/local/bin/sha512sum

```
$ brew install coreutils
$ ln -s /usr/local/bin/gsha512sum /usr/local/bin/sha512sum

$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.

$ sudo ./protonvpn-cli.sh -c us-ca#1 tcp
Fetching ProtonVPN Servers...
Connecting...
[$] Connected!
[#] New IP: 209.58.129.97
```

**Comment by mazen160** [comment]
@cantab412 Awesome!!
