### ISSUE TITLE
protonvpn-cli cannot handle DHCP-assigned DNS servers on macOS

### ISSUE THREAD

**Issue by xilopaint** [ProtonVPN/protonvpn-cli#51]
The issue is shortly described [here](https://blog.netnerds.net/2011/10/openvpn-update-client-dns-on-mac-os-x-using-from-the-command-line/):

> There’s a bit of a debate on how best to update your DNS resolver on Mac OS X when connecting to an OpenVPN Server. For whatever reason, even if use DHCP on the VPN server, OS X won’t use the assigned DNS server(s). It’s been recommended to use scutil, but the scripts are crazy long and I’ve read the resolver order sometimes gets reset anyway.
> 
> The usual route of using /etc/resolv.conf does not work on OS X but specifying DNS servers in your Network Preferences does.

The solution is using `scutil`, mostly recommended and used by Tunnelblick, or `networksetup` for a shorter approach.

**Comment by xilopaint** [comment]
In the meantime I have submitted # 50 in order to prevent update-resolv-conf be installed in macOS as well as resolv.conf be changed, since useless.

**Comment by cantab412** [comment]
Hi @xilopaint -

I am in no way a developer or network guy and am just trying to help out. My normal network config is using DHCP from my home router (192.168.1.1).  The router uses a couple of OpenNIC DNS servers.

I've attached the output of `scutil --dns` taken from my system using some different VPN tools.  Not sure if this is useful?

Not connected to any VPN, just running normally:  [no-vpn.txt](https://github.com/ProtonVPN/protonvpn-cli/files/1854717/no-vpn.txt)

Connected via the ProtonVPN Mac app:  [proton-app.txt](https://github.com/ProtonVPN/protonvpn-cli/files/1854718/proton-app.txt)

Connected via proton-cli.sh:  [proton-cli.txt](https://github.com/ProtonVPN/protonvpn-cli/files/1854719/proton-cli.txt)

Connected via Tunnelblick:  [tunnelblick.txt](https://github.com/ProtonVPN/protonvpn-cli/files/1854720/tunnelblick.txt)

Connected via Witopia (uses Viscosity):  [witopia.txt](https://github.com/ProtonVPN/protonvpn-cli/files/1854721/witopia.txt)

**Comment by xilopaint** [comment]
It seems to confirm the issue.

Are you connected to Wi-Fi? If so, connect to protonvpn-cli and tell me if your output for `networksetup -getdnsservers Wi-Fi` shows 192.168.1.1 or your OpenNIC DNS servers.

After that, try removing your OpenNIC DNS servers from your router settings and tell me if protonvpn-cli works. If not, the issue is confirmed.

**Comment by cantab412** [comment]
@xilopaint Yes, on wi-fi in the house.

I am going to be AFK until late Sunday, but will test the DNS scenarios you requested on my return.

**Comment by mazen160** [comment]
This issue is moved to https://github.com/ProtonVPN/protonvpn-cli/issues/65
