### ISSUE TITLE
Using standard UNIX CLI conventions

### ISSUE THREAD

**Issue by kaplun** [ProtonVPN/protonvpn-cli#53]
Hi!

`protonvpn-cli` is great! Would it be possible to amend the CLI arguments to follow traditional standard of:

* `-f` short form
* `--foo` long form

This would make it more consistent with all the other UNIX tools.
In particular for `-connect`, `-fastest-connect`, `-disconnect`, `-ip`, `-update`, `-install`, `-uninstall`.

**Comment by mazen160** [comment]
Hi @kaplun 

Thanks for making a ticket!

I had this in mind, but I thought about making it simpler.

`-c`, `-connect`, `--connect` all do the same function for example. 

but `-c`, `-connect` are used on usage page for simplicity.

We can keep it this ticket open for a week. If we receive votes on changing it, I would be happy to change it.

Thanks,
Mazin

**Comment by Rafficer** [comment]
Voting for changing it to using standard conventions.

**Comment by kaplun** [comment]
Nice indeed if you can support all formats. In the end there are not yet so many arguments. It's just that the help page was making my OCD to surface :rofl:

**Comment by Rafficer** [comment]
That's precisely the issue. OCD. :P

**Comment by cantab412** [comment]
Voting for changing it to using standard conventions.

**Comment by xilopaint** [comment]
> Voting for changing it to using standard conventions.

+1

**Comment by webmaniak** [comment]
Also voting for using the standard convention.

By the way, thank you for such a promising tool. It's really young but I already like it :smile:

**Comment by mazen160** [comment]
Done! :smile:
