### ISSUE TITLE
Secure Core feature

### ISSUE THREAD

**Issue by webmaniak** [ProtonVPN/protonvpn-cli#55]
Hello!

First of all, thank you for this young but promising tool. I'm looking forward to seeing how it will evolve.

Secondly, it's more a question than an issue but how can someone distinguish a regular node from a node of the Secure Core environment? Is this feature already implemented in protonvpn-cli? Is there already a publicly accessible roadmap?

Thanks for your answers.

**Comment by Rafficer** [comment]
When connecting? Use `pvpn -c` and then scroll down. On the right column it shows features, which is either none, secure core, tor or P2P.

**Comment by mazen160** [comment]
Hi @webmaniak !

Thank you for checking protonvpn-cli!!

> Secondly, it's more a question than an issue but how can someone distinguish a regular node from a node of the Secure Core environment? Is this feature already implemented in protonvpn-cli?

Yes, it's already included in protonvpn-cli. You can see  Secure-Core servers when running `pvpn -c` on features section on the menu.  Other features are also stated.

**Comment by mazen160** [comment]
Yup, as @Rafficer said :)

**Comment by webmaniak** [comment]
@Rafficer and @mazen160 : Thank you very much for your explanation, that's way clearer for me now!

**Comment by mazen160** [comment]
@webmaniak Anytime!! :)
