### ISSUE TITLE
Uninstallation leaves current OpenVPN session running

### ISSUE THREAD

**Issue by Rafficer** [ProtonVPN/protonvpn-cli#58]
When uninstalling the program while currently connected, it leaves the user without an option to disconnect the session after that (except manually finding and killing the process)

**Comment by mazen160** [comment]
@Rafficer Nice one! 

That's an interesting bug for sure.

**Comment by mazen160** [comment]
@Rafficer Would you mind email or DM? I am trying to contact you but I didn't find your email. my email is: mazin at protonmail ch
