### ISSUE TITLE
Install fails if /usr/local/bin/ doesn't exist

### ISSUE THREAD

**Issue by different55** [ProtonVPN/protonvpn-cli#64]
```
function install_cli() {
  mkdir -p "/usr/bin/"
  cli="$( cd "$(dirname "$0")" ; pwd -P )/$0"
  errors_counter=0
  cp "$cli" "/usr/local/bin/protonvpn-cli" &> /dev/null
  if [[ $? != 0 ]]; then errors_counter=$((errors_counter+1)); fi

  ln -s -f "/usr/local/bin/protonvpn-cli" "/usr/local/bin/pvpn" &> /dev/null
  if [[ $? != 0 ]]; then errors_counter=$((errors_counter+1)); fi

  ln -s -f "/usr/local/bin/protonvpn-cli" "/usr/bin/protonvpn-cli" &> /dev/null
  if [[ $? != 0 ]]; then errors_counter=$((errors_counter+1)); fi

  ln -s -f "/usr/local/bin/protonvpn-cli" "/usr/bin/pvpn" &> /dev/null
  if [[ $? != 0 ]]; then errors_counter=$((errors_counter+1)); fi

  chown "$USER:$(id -gn $USER)" "/usr/local/bin/protonvpn-cli" "/usr/local/bin/pvpn" "/usr/bin/protonvpn-cli" "/usr/bin/pvpn" &> /dev/null
  if [[ $? != 0 ]]; then errors_counter=$((errors_counter+1)); fi

  chmod 0755 "/usr/local/bin/protonvpn-cli" "/usr/local/bin/pvpn" "/usr/bin/protonvpn-cli" "/usr/bin/pvpn" &> /dev/null
  if [[ $? != 0 ]]; then errors_counter=$((errors_counter+1)); fi

  if [[ ($errors_counter == 0) || ( $(which protonvpn-cli) != "" ) ]]; then
    echo "[*] Done."
  else
    echo "[!] Error: There was an error in installing protonvpn-cli."
  fi
}
```

The script tries to create /usr/bin, then copies itself to /usr/**local**/bin, which might not exist on all distros (like Solus), and the script doesn't try to create it. And if this first copy fails, all the others do as well since it tries to copy from the failed location.

**Comment by xilopaint** [comment]
Try to change `mkdir -p "/usr/bin/"` to `mkdir -p "/usr/local/bin/"`.

If it doesn't work because properly because of the the issue with sudo reported in #12 we will need to back to use `/usr/bin/` as installation directory.

I really don't understand why it was changed in e31a5ff2c76a83ce298d9f6c9f3132db8dcc0167.

**Comment by different55** [comment]
Swapping that out makes it work just fine. I don't have the same problem as in #12. I'm guessing since it's also later copied to /usr/bin/ which is in PATH across the board. `which protonvpn-cli` points towards /usr/bin for both root and my regular user.

-------- Original Message --------

**Comment by xilopaint** [comment]
> `which protonvpn-cli` points towards /usr/bin for both root and my regular user.

And what do you get for `sudo which protonvpn-cli`?

**Comment by different55** [comment]
`/usr/bin/protonvpn-cli` as well

**Comment by xilopaint** [comment]
Is your distro Solus?

**Comment by mazen160** [comment]
@different55 Which distro are you using?

@xilopaint  The commit you mentioned was added for backward compatibility for a Solus OS bug.

**Comment by mazen160** [comment]
Hi @different55 

The issue should be fixed. For reference, It would be great if you can let us know the distro you are using.

Thanks for reporting it!

Best,
Mazin

**Comment by xilopaint** [comment]
> @xilopaint The commit you mentioned was added for backward compatibility for a Solus OS bug.

How can it solves the compatibility issue with Solus? This system doesn't have `/usr/local/bin/` created in most installations as far as we can see here, so you can't change the installation directory from `/usr/bin/` to `/usr/local/bin` without creating the latter in the first place.

**Comment by mazen160** [comment]
@xilopaint 
This how it adds backward compatibility for OSs that have these issues.
Systems mostly have `/usr/local/bin` and `/usr/bin` in `PATH`, or one of them in odd cases.

What I did is:

1. If the directories are not there, create them
2. install protonvpn-cli in a directory, while making a symlink in the other directory just in case one failed to be in PATH. 

This way it should satisfy odd systems.

**Comment by xilopaint** [comment]
Sorry, but I really don't get how it could work. We knew that some Solus users didn't have the `/usr/local/bin/` directory in their machines. The code implemented in e31a5ff2c76a83ce298d9f6c9f3132db8dcc0167 was:

```
function install_cli() {
  mkdir -p "/usr/bin/"
  cli="$( cd "$(dirname "$0")" ; pwd -P )/$0"
  errors_counter=0
  cp "$cli" "/usr/local/bin/protonvpn-cli" &> /dev/null
```

The `cp` command fails because `/usr/local/bin/` is not present. That commit just fixed the `sudo` issue for the users that already had `/usr/local/bin` created for a previous commit that used `mkdir -p "/usr/local/bin/"` (subsequently replaced for `mkdir -p "/usr/local/bin/"`).

**Comment by mazen160** [comment]
@xilopaint Yes, I added an addition to change this ;)
https://github.com/ProtonVPN/protonvpn-cli/commit/8e024fe623e3e76a28b08679af893513aeb4d14f

**Comment by different55** [comment]
@mazen160 I am using Solus.

**Comment by mazen160** [comment]
@different55 Thanks for letting us know. The bug should be fixed now!
