### ISSUE TITLE
ProtonVPN dies on suspend/disconnected internet

### ISSUE THREAD

**Issue by different55** [ProtonVPN/protonvpn-cli#68]
protonvpn-cli doesn't seem to ever recover if a computer loses its internet connection, even for a moment. Both suspending the computer and disconnecting/reconnecting to the same (or a different) wifi network will do the trick.

After that happens, any requests just kind of hang out in limbo until it times out or until you run `protonvpn-cli -d`.

It's nice that protonvpn doesn't allow any connections when the VPN connection dies, but it should be able to get back up on its own. Shutting it off to restart it allows all the stuff it's been blocking to slip through.

**Comment by mazen160** [comment]
Hi @different55 
Thanks for reporting the issue. This is an expected behaviour. More of a security feature to prevent fatal risk of having the traffic leaks.

We will have this ticket open until we figure an idea that can help preventing this, while not breaking built-in security.


Best,
Mazin

**Comment by mazen160** [comment]
If anyone have an idea, feel free to share it with us.

**Comment by mazen160** [comment]
Moving ticket to https://github.com/ProtonVPN/protonvpn-cli/issues/69
