### ISSUE TITLE
changed nameserver now wont connect

### ISSUE THREAD

**Issue by akrolla** [ProtonVPN/protonvpn-cli#74]
changed to Cloudflare's new encrypted dns nameserver 1.1.1.1 / 1.0.0.1 and it isnt allowng internet connection now using any of the ovpn configs

**Comment by Rafficer** [comment]
What distro are you using and how exactly did you change it?

**Comment by xilopaint** [comment]
These DNS servers are working for me with protonvpn-cli.

**Comment by mazen160** [comment]
Hi @akrolla 


This seems to be a false-positive. To rechange DNS configurations with protonvpn-cli, you should rechange it after connecting to a server, but this would lead you to potential DNS leaks.

Best,
Mazin
