### ISSUE TITLE
Error during connect - .ipv6_address: No such file or directory

### ISSUE THREAD

**Issue by borra** [ProtonVPN/protonvpn-cli#75]
Hi,

Getting this error when trying to start the VPN. Running on Debian 8.x.
Connecting…
[!] Error connecting to VPN.
/usr/local/bin/protonvpn-cli: line 170: /root/.protonvpn-cli//.ipv6_address: No such file or directory
Tried as root or normal user using sudo. Same error. IPv6 is disabled.

Thank you,
rborsaru

**Comment by xilopaint** [comment]
I guess you're not using the latest version of the workflow. Try `sudo pvpn --update`.

**Comment by borra** [comment]
Gettiing last code from github solved the problem.

Thank you.
