### ISSUE TITLE
Error connecting to VPN on Ubuntu 17.10

### ISSUE THREAD

**Issue by pwlodarczak** [ProtonVPN/protonvpn-cli#79]
Hi,
I have been trying protonvpn-cli on Ubuntu 17.10 since the OpenVPN client has DNS leaks. When I try to connect using:
`protonvpn-cli -c`
I can select a VPN server and protocol, but whichever server I select I get:

> Connecting...
[!] Error connecting to VPN.
[!] There are issues in managing IPv6 in the system. Please test the system for the root cause.
Not being able to manage IPv6 by protonvpn-cli might cause issues in leaking the system's IPv6 address.

How can I fix this?
Regards 
Peter

**Comment by Rafficer** [comment]
Seems to be the same issue as #77, no?

**Comment by pwlodarczak** [comment]
Yes it is, and there is no solution.

**Comment by Rafficer** [comment]
Please refer to the other issue then and follow it, we don't need multiple issues for the same problem and can have one conversation over there. Can you close this one?
