### ISSUE TITLE
IPv6 issue - Debian 8.x

### ISSUE THREAD

**Issue by borra** [ProtonVPN/protonvpn-cli#81]
Getting following error when trying to connect:
I have tried to disable IPv6 as per your blogpost and the same error.
Connecting...
[!] Error connecting to VPN.
[!] There are issues in managing IPv6 in the system. Please test the system for the root cause.
Not being able to manage IPv6 by protonvpn-cli might cause issues in leaking the system's IPv6 address.

Thank you.

**Comment by Rafficer** [comment]
Please close this issue and refer to #77

**Comment by borra** [comment]
Duplicate of #77.
