### ISSUE TITLE
Enhancement: Add Protonvpn-cli to debian repos

### ISSUE THREAD

**Issue by oonimooni** [ProtonVPN/protonvpn-cli#82]
Please upload ProtonVPN-Cli to Debian repos so it can be downloaded and installed easily and safely.

**Comment by Rafficer** [comment]
Isn't this basically #27? And it isn't that easy to add stuff to the official debian repos, is it?

**Comment by njfox** [comment]
I'm pretty sure it takes literally years to get a package into Debian stable.

**Comment by oonimooni** [comment]
> Isn't this basically #27?

yeah it is , sorry didnt know it exist already. 

> And it isn't that easy to add stuff to the official debian repos, is it?

Correct, but thats shouldnt be a problem for a payable service talking about anonymity/privacy no? 

add to this it will add an authentication credit for ProtonVPN to have it on the official repo of debian.

**Comment by Rafficer** [comment]
Please close this issue then and refer to 27 for discussions.

**Comment by oonimooni** [comment]
#27
