### ISSUE TITLE
SInce When Tor Supporting UDP

### ISSUE THREAD

**Issue by oonimooni** [ProtonVPN/protonvpn-cli#83]
when i connect to Tor servers which r available in VPN list it shows which type of connections i should choose UDP or TCP , and im wondering when was Tor running through UDP ??? (unless its not Tor)

**Comment by mazen160** [comment]
Hi @oonimooni 

So the concept is relatively simple. You connect to Protonvpn-TOR server, traffic is routed through TOR. You can confirm that by yourself :)

I understand it may seem confusing, but this is happening in the background to give this experience.

**Comment by oonimooni** [comment]
? can u be more technical please? 

r u tunneling user connection through Tor then ProtonVPN then the website ?

or

user -> VPN -> Tor -> Website ? 

because simply Tor wont ever connect u through UDP due to architecture design restrictions.

**Comment by Rafficer** [comment]
> user -> VPN -> Tor -> Website ?

This.
