### ISSUE TITLE
use user privilege/level instead of root 

### ISSUE THREAD

**Issue by oonimooni** [ProtonVPN/protonvpn-cli#93]
running protonvpn-cli needs root privilege and thats not recommended from security pointview. 

e.g to learn from: running Tor or i2p or freenet or airvpn ..etc they dent require root privilege to make it running.

**Comment by Rafficer** [comment]
1. Root is required for OpenVPN, there's no way around it.

2. The credentials are only accessible by root for security.

**Comment by mazen160** [comment]
Yes, changing the module will break security for protonvpn-cli. Risk model relies on openvpn as the attack surface, allowing non-root users to execute pvpn opens additional surface. A workaround is to whitelist `openvpn` in sudoers, but I personally don't recommend it.
