### ISSUE TITLE
tcp vs udp

### ISSUE THREAD

**Issue by jQrgen** [ProtonVPN/protonvpn-cli#96]
Why do we choose between tcp and udp? 

What are the advantages and disadvantages of using tcp and udp with protonvpn cli?

**Comment by ATI-RV350** [comment]
This isn't an issue, nor is it unique to ProtonVPN. You can find the answer quite easily via search engine.

Using TCP can circumvent censorship or network issues at times, and can be more reliable but generally has more overhead than UDP, although performance can vary between the two.

You should use UDP unless you specifically have issues with it.

**Comment by jQrgen** [comment]
Thanks.
