### ISSUE TITLE
Cannot open TUN/TAP dev /dev/net/tun

### ISSUE THREAD

**Issue by Bloopps** [ProtonVPN/protonvpn-cli#99]
Hi

I have this error ` ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2` when I run the command` ./protonvpn-cli.sh -f` but only on a Debian container in Proxmox Virtual Environment.
I do the same thing in a Debian 9 environment without Proxmox virtual environment and everything works fine.

  the log file `PROTONVPN_CLI_LOG=true ./protonvpn-cli.sh -f` :
[Log_Protoncli.txt](https://github.com/ProtonVPN/protonvpn-cli/files/1965478/Log_Protoncli.txt)

Thanks for your help

**Comment by mazen160** [comment]
Hi @Bloopps
This is probably either a kernel related issue, or permission related.

Can you do the following:
```
$ sudo su
$ id
$ pvpn -update
$ pvpn -f
```
and if it's still not working, can you share the output?

**Comment by mazen160** [comment]
Can you try to connect with manual openvpn config?
The bug is definitely appearing in an odd configuration on you machine's end.

**Comment by Bloopps** [comment]
Hi @mazen160 
Sorry I didn't answer before
Here is a test in manual connect with openvpn config =>[openvpncli.log](https://github.com/ProtonVPN/protonvpn-cli/files/2077366/openvpncli.log)

**Comment by mazen160** [comment]
Hi @Bloopps 
I have checked the issues with the team. It appears to be an issue in your setup (from your end).

It's a container issue where no dev/tun device is created.

Please refer to the following references to get an idea about the issue:
* https://wiki.openvz.org/VPN_via_the_TUN/TAP_device
* https://serverfault.com/questions/429461/no-tun-device-in-lxc-guest-for-openvpn#429467
* https://forum.proxmox.com/threads/openvpn-tun-tap-device-cannot-open-tun-tap-dev-dev-net-tun-no-such-file-or-directory-errno-2.25990/


Best regards,
Mazin

**Comment by Bloopps** [comment]
Hi, I finally solved my problem with this:

- [https://vroomtech.io/enable-tuntap-in-a-proxmox-lxc-container/](url)

Protonvpn-cli works perfectly now
Thanks @mazen160  for your help !

**Comment by mazen160** [comment]
Hi @Bloopps 
Great!! Totally glad to help!:)
